// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

async function runHelm(args) {
  let cmd = $$Deno.Command.$$new("helm", args, undefined);
  let output = await cmd.output();
  if (output.success) {
    return {
      TAG: "Ok",
      _0: $$Deno.Command.stdoutText(output)
    };
  } else {
    return {
      TAG: "Error",
      _0: $$Deno.Command.stderrText(output)
    };
  }
}

let tools = Object.fromEntries([
  [
    "helm_install",
    {
      name: "helm_install",
      description: "Install a Helm chart",
      inputSchema: {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "Release name" },
        "chart": { "type": "string", "description": "Chart reference (repo/chart or path)" },
        "namespace": { "type": "string", "description": "Kubernetes namespace" },
        "values": { "type": "object", "description": "Values to override (key-value pairs)" },
        "valuesFile": { "type": "string", "description": "Path to values file" },
        "version": { "type": "string", "description": "Chart version" },
        "createNamespace": { "type": "boolean", "description": "Create namespace if not exists" },
        "dryRun": { "type": "boolean", "description": "Simulate installation" },
        "wait": { "type": "boolean", "description": "Wait for resources to be ready" }
      },
      "required": ["name", "chart"]
    }
    }
  ],
  [
    "helm_upgrade",
    {
      name: "helm_upgrade",
      description: "Upgrade a Helm release",
      inputSchema: {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "Release name" },
        "chart": { "type": "string", "description": "Chart reference" },
        "namespace": { "type": "string", "description": "Kubernetes namespace" },
        "values": { "type": "object", "description": "Values to override" },
        "valuesFile": { "type": "string", "description": "Path to values file" },
        "version": { "type": "string", "description": "Chart version" },
        "install": { "type": "boolean", "description": "Install if release doesn't exist" },
        "dryRun": { "type": "boolean", "description": "Simulate upgrade" },
        "wait": { "type": "boolean", "description": "Wait for resources to be ready" },
        "reuseValues": { "type": "boolean", "description": "Reuse existing values" }
      },
      "required": ["name", "chart"]
    }
    }
  ],
  [
    "helm_uninstall",
    {
      name: "helm_uninstall",
      description: "Uninstall a Helm release",
      inputSchema: {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "Release name" },
        "namespace": { "type": "string", "description": "Kubernetes namespace" },
        "keepHistory": { "type": "boolean", "description": "Keep release history" },
        "dryRun": { "type": "boolean", "description": "Simulate uninstall" }
      },
      "required": ["name"]
    }
    }
  ],
  [
    "helm_list",
    {
      name: "helm_list",
      description: "List Helm releases",
      inputSchema: {
      "type": "object",
      "properties": {
        "namespace": { "type": "string", "description": "Kubernetes namespace" },
        "allNamespaces": { "type": "boolean", "description": "List across all namespaces" },
        "filter": { "type": "string", "description": "Filter by release name regex" },
        "deployed": { "type": "boolean", "description": "Show deployed releases only" },
        "failed": { "type": "boolean", "description": "Show failed releases only" },
        "pending": { "type": "boolean", "description": "Show pending releases only" }
      }
    }
    }
  ],
  [
    "helm_status",
    {
      name: "helm_status",
      description: "Get status of a Helm release",
      inputSchema: {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "Release name" },
        "namespace": { "type": "string", "description": "Kubernetes namespace" },
        "revision": { "type": "integer", "description": "Specific revision" }
      },
      "required": ["name"]
    }
    }
  ],
  [
    "helm_history",
    {
      name: "helm_history",
      description: "Get release history",
      inputSchema: {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "Release name" },
        "namespace": { "type": "string", "description": "Kubernetes namespace" },
        "max": { "type": "integer", "description": "Maximum revisions to show" }
      },
      "required": ["name"]
    }
    }
  ],
  [
    "helm_rollback",
    {
      name: "helm_rollback",
      description: "Rollback a release to a previous revision",
      inputSchema: {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "Release name" },
        "revision": { "type": "integer", "description": "Revision number to rollback to" },
        "namespace": { "type": "string", "description": "Kubernetes namespace" },
        "dryRun": { "type": "boolean", "description": "Simulate rollback" },
        "wait": { "type": "boolean", "description": "Wait for resources to be ready" }
      },
      "required": ["name", "revision"]
    }
    }
  ],
  [
    "helm_repo_add",
    {
      name: "helm_repo_add",
      description: "Add a Helm chart repository",
      inputSchema: {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "Repository name" },
        "url": { "type": "string", "description": "Repository URL" },
        "username": { "type": "string", "description": "Username for auth" },
        "password": { "type": "string", "description": "Password for auth" },
        "forceUpdate": { "type": "boolean", "description": "Replace existing repo" }
      },
      "required": ["name", "url"]
    }
    }
  ],
  [
    "helm_repo_list",
    {
      name: "helm_repo_list",
      description: "List configured Helm repositories",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "helm_repo_update",
    {
      name: "helm_repo_update",
      description: "Update Helm repository cache",
      inputSchema: {
      "type": "object",
      "properties": {
        "repos": { "type": "array", "items": { "type": "string" }, "description": "Specific repos to update" }
      }
    }
    }
  ],
  [
    "helm_search",
    {
      name: "helm_search",
      description: "Search for Helm charts",
      inputSchema: {
      "type": "object",
      "properties": {
        "keyword": { "type": "string", "description": "Search keyword" },
        "source": { "type": "string", "enum": ["repo", "hub"], "description": "Search repos or Artifact Hub" },
        "version": { "type": "string", "description": "Version constraint" },
        "versions": { "type": "boolean", "description": "Show all versions" }
      },
      "required": ["keyword"]
    }
    }
  ],
  [
    "helm_show",
    {
      name: "helm_show",
      description: "Show chart information (values, readme, chart)",
      inputSchema: {
      "type": "object",
      "properties": {
        "chart": { "type": "string", "description": "Chart reference" },
        "info": { "type": "string", "enum": ["all", "chart", "readme", "values", "crds"], "description": "What to show" },
        "version": { "type": "string", "description": "Chart version" }
      },
      "required": ["chart"]
    }
    }
  ],
  [
    "helm_template",
    {
      name: "helm_template",
      description: "Render chart templates locally",
      inputSchema: {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "Release name" },
        "chart": { "type": "string", "description": "Chart reference" },
        "values": { "type": "object", "description": "Values to override" },
        "valuesFile": { "type": "string", "description": "Path to values file" },
        "version": { "type": "string", "description": "Chart version" },
        "namespace": { "type": "string", "description": "Namespace for resources" }
      },
      "required": ["name", "chart"]
    }
    }
  ],
  [
    "helm_get",
    {
      name: "helm_get",
      description: "Get release information (values, manifest, notes, hooks)",
      inputSchema: {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "Release name" },
        "info": { "type": "string", "enum": ["all", "values", "manifest", "notes", "hooks"], "description": "What to get" },
        "namespace": { "type": "string", "description": "Kubernetes namespace" },
        "revision": { "type": "integer", "description": "Specific revision" }
      },
      "required": ["name"]
    }
    }
  ]
]);

async function handleToolCall(name, args) {
  let argsDict = Stdlib_Option.getOr(Stdlib_JSON.Decode.object(args), {});
  let getString = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.string), "");
  let getBool = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.bool), false);
  let getInt = key => Stdlib_Option.map(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.float), v => v | 0);
  let ns = getString("namespace");
  let nsArg = ns !== "" ? [
      "-n",
      ns
    ] : [];
  switch (name) {
    case "helm_get" :
      let relName = getString("name");
      let info = getString("info");
      let revision = getInt("revision");
      let getCmd = info !== "" ? info : "all";
      let args$1 = [
        "get",
        getCmd,
        relName
      ];
      let args$2 = args$1.concat(nsArg);
      let args$3 = revision !== undefined ? args$2.concat([
          "--revision",
          revision.toString()
        ]) : args$2;
      return await runHelm(args$3);
    case "helm_history" :
      let relName$1 = getString("name");
      let max = getInt("max");
      let args$4 = [
        "history",
        relName$1
      ];
      let args$5 = args$4.concat(nsArg);
      let args$6 = max !== undefined ? args$5.concat([
          "--max",
          max.toString()
        ]) : args$5;
      return await runHelm(args$6);
    case "helm_install" :
      let relName$2 = getString("name");
      let chart = getString("chart");
      let version = getString("version");
      let valuesFile = getString("valuesFile");
      let createNs = getBool("createNamespace");
      let dryRun = getBool("dryRun");
      let wait = getBool("wait");
      let args$7 = [
        "install",
        relName$2,
        chart
      ];
      let args$8 = args$7.concat(nsArg);
      let args$9 = version !== "" ? args$8.concat([
          "--version",
          version
        ]) : args$8;
      let args$10 = valuesFile !== "" ? args$9.concat([
          "-f",
          valuesFile
        ]) : args$9;
      let args$11 = createNs ? args$10.concat(["--create-namespace"]) : args$10;
      let args$12 = dryRun ? args$11.concat(["--dry-run"]) : args$11;
      let args$13 = wait ? args$12.concat(["--wait"]) : args$12;
      return await runHelm(args$13);
    case "helm_list" :
      let allNs = getBool("allNamespaces");
      let filter = getString("filter");
      let deployed = getBool("deployed");
      let failed = getBool("failed");
      let pending = getBool("pending");
      let args$14 = ["list"];
      let args$15 = allNs ? args$14.concat(["--all-namespaces"]) : args$14.concat(nsArg);
      let args$16 = filter !== "" ? args$15.concat([
          "--filter",
          filter
        ]) : args$15;
      let args$17 = deployed ? args$16.concat(["--deployed"]) : args$16;
      let args$18 = failed ? args$17.concat(["--failed"]) : args$17;
      let args$19 = pending ? args$18.concat(["--pending"]) : args$18;
      return await runHelm(args$19);
    case "helm_repo_add" :
      let repoName = getString("name");
      let url = getString("url");
      let username = getString("username");
      let password = getString("password");
      let forceUpdate = getBool("forceUpdate");
      let args$20 = [
        "repo",
        "add",
        repoName,
        url
      ];
      let args$21 = username !== "" ? args$20.concat([
          "--username",
          username
        ]) : args$20;
      let args$22 = password !== "" ? args$21.concat([
          "--password",
          password
        ]) : args$21;
      let args$23 = forceUpdate ? args$22.concat(["--force-update"]) : args$22;
      return await runHelm(args$23);
    case "helm_repo_list" :
      return await runHelm([
        "repo",
        "list"
      ]);
    case "helm_repo_update" :
      return await runHelm([
        "repo",
        "update"
      ]);
    case "helm_rollback" :
      let relName$3 = getString("name");
      let revision$1 = Stdlib_Option.getOr(getInt("revision"), 0);
      let dryRun$1 = getBool("dryRun");
      let wait$1 = getBool("wait");
      let args$24 = [
        "rollback",
        relName$3,
        revision$1.toString()
      ];
      let args$25 = args$24.concat(nsArg);
      let args$26 = dryRun$1 ? args$25.concat(["--dry-run"]) : args$25;
      let args$27 = wait$1 ? args$26.concat(["--wait"]) : args$26;
      return await runHelm(args$27);
    case "helm_search" :
      let keyword = getString("keyword");
      let source = getString("source");
      let version$1 = getString("version");
      let versions = getBool("versions");
      let searchCmd = source === "hub" ? "hub" : "repo";
      let args$28 = [
        "search",
        searchCmd,
        keyword
      ];
      let args$29 = version$1 !== "" ? args$28.concat([
          "--version",
          version$1
        ]) : args$28;
      let args$30 = versions ? args$29.concat(["--versions"]) : args$29;
      return await runHelm(args$30);
    case "helm_show" :
      let chart$1 = getString("chart");
      let info$1 = getString("info");
      let version$2 = getString("version");
      let showCmd = info$1 !== "" ? info$1 : "all";
      let args$31 = [
        "show",
        showCmd,
        chart$1
      ];
      let args$32 = version$2 !== "" ? args$31.concat([
          "--version",
          version$2
        ]) : args$31;
      return await runHelm(args$32);
    case "helm_status" :
      let relName$4 = getString("name");
      let revision$2 = getInt("revision");
      let args$33 = [
        "status",
        relName$4
      ];
      let args$34 = args$33.concat(nsArg);
      let args$35 = revision$2 !== undefined ? args$34.concat([
          "--revision",
          revision$2.toString()
        ]) : args$34;
      return await runHelm(args$35);
    case "helm_template" :
      let relName$5 = getString("name");
      let chart$2 = getString("chart");
      let version$3 = getString("version");
      let valuesFile$1 = getString("valuesFile");
      let args$36 = [
        "template",
        relName$5,
        chart$2
      ];
      let args$37 = args$36.concat(nsArg);
      let args$38 = version$3 !== "" ? args$37.concat([
          "--version",
          version$3
        ]) : args$37;
      let args$39 = valuesFile$1 !== "" ? args$38.concat([
          "-f",
          valuesFile$1
        ]) : args$38;
      return await runHelm(args$39);
    case "helm_uninstall" :
      let relName$6 = getString("name");
      let keepHistory = getBool("keepHistory");
      let dryRun$2 = getBool("dryRun");
      let args$40 = [
        "uninstall",
        relName$6
      ];
      let args$41 = args$40.concat(nsArg);
      let args$42 = keepHistory ? args$41.concat(["--keep-history"]) : args$41;
      let args$43 = dryRun$2 ? args$42.concat(["--dry-run"]) : args$42;
      return await runHelm(args$43);
    case "helm_upgrade" :
      let relName$7 = getString("name");
      let chart$3 = getString("chart");
      let version$4 = getString("version");
      let valuesFile$2 = getString("valuesFile");
      let install = getBool("install");
      let dryRun$3 = getBool("dryRun");
      let wait$2 = getBool("wait");
      let reuseValues = getBool("reuseValues");
      let args$44 = [
        "upgrade",
        relName$7,
        chart$3
      ];
      let args$45 = args$44.concat(nsArg);
      let args$46 = version$4 !== "" ? args$45.concat([
          "--version",
          version$4
        ]) : args$45;
      let args$47 = valuesFile$2 !== "" ? args$46.concat([
          "-f",
          valuesFile$2
        ]) : args$46;
      let args$48 = install ? args$47.concat(["--install"]) : args$47;
      let args$49 = dryRun$3 ? args$48.concat(["--dry-run"]) : args$48;
      let args$50 = wait$2 ? args$49.concat(["--wait"]) : args$49;
      let args$51 = reuseValues ? args$50.concat(["--reuse-values"]) : args$50;
      return await runHelm(args$51);
    default:
      return {
        TAG: "Error",
        _0: "Unknown tool: " + name
      };
  }
}

export {
  runHelm,
  tools,
  handleToolCall,
}
/* tools Not a pure module */
