// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let namespace = {
  contents: "default"
};

async function runKubectl(args) {
  let cmd = $$Deno.Command.$$new("kubectl", args, undefined);
  let output = await cmd.output();
  if (output.success) {
    return {
      TAG: "Ok",
      _0: $$Deno.Command.stdoutText(output)
    };
  } else {
    return {
      TAG: "Error",
      _0: $$Deno.Command.stderrText(output)
    };
  }
}

let tools = Object.fromEntries([
  [
    "kubectl_get",
    {
      name: "kubectl_get",
      description: "Get Kubernetes resources (pods, deployments, services, etc.)",
      inputSchema: {
      "type": "object",
      "properties": {
        "resource": { "type": "string", "description": "Resource type (pods, deployments, services, configmaps, secrets, nodes, namespaces, etc.)" },
        "name": { "type": "string", "description": "Optional resource name" },
        "namespace": { "type": "string", "description": "Namespace (default: current)" },
        "selector": { "type": "string", "description": "Label selector (e.g., app=nginx)" },
        "output": { "type": "string", "enum": ["wide", "yaml", "json", "name"], "description": "Output format" },
        "allNamespaces": { "type": "boolean", "description": "List across all namespaces" }
      },
      "required": ["resource"]
    }
    }
  ],
  [
    "kubectl_describe",
    {
      name: "kubectl_describe",
      description: "Show detailed information about a Kubernetes resource",
      inputSchema: {
      "type": "object",
      "properties": {
        "resource": { "type": "string", "description": "Resource type" },
        "name": { "type": "string", "description": "Resource name" },
        "namespace": { "type": "string", "description": "Namespace" }
      },
      "required": ["resource", "name"]
    }
    }
  ],
  [
    "kubectl_logs",
    {
      name: "kubectl_logs",
      description: "Print logs from a container in a pod",
      inputSchema: {
      "type": "object",
      "properties": {
        "pod": { "type": "string", "description": "Pod name" },
        "container": { "type": "string", "description": "Container name (if multiple)" },
        "namespace": { "type": "string", "description": "Namespace" },
        "tail": { "type": "integer", "description": "Number of lines from end" },
        "since": { "type": "string", "description": "Only logs newer than duration (e.g., 5m, 1h)" },
        "follow": { "type": "boolean", "description": "Stream logs (returns snapshot)" },
        "previous": { "type": "boolean", "description": "Print previous instance logs" }
      },
      "required": ["pod"]
    }
    }
  ],
  [
    "kubectl_apply",
    {
      name: "kubectl_apply",
      description: "Apply a configuration to a resource from a file or stdin",
      inputSchema: {
      "type": "object",
      "properties": {
        "manifest": { "type": "string", "description": "YAML or JSON manifest content" },
        "filename": { "type": "string", "description": "Path to manifest file" },
        "namespace": { "type": "string", "description": "Namespace" },
        "dryRun": { "type": "boolean", "description": "Run in dry-run mode (client or server)" }
      }
    }
    }
  ],
  [
    "kubectl_delete",
    {
      name: "kubectl_delete",
      description: "Delete Kubernetes resources",
      inputSchema: {
      "type": "object",
      "properties": {
        "resource": { "type": "string", "description": "Resource type" },
        "name": { "type": "string", "description": "Resource name" },
        "namespace": { "type": "string", "description": "Namespace" },
        "selector": { "type": "string", "description": "Label selector" },
        "force": { "type": "boolean", "description": "Force deletion" },
        "gracePeriod": { "type": "integer", "description": "Grace period in seconds" }
      },
      "required": ["resource"]
    }
    }
  ],
  [
    "kubectl_exec",
    {
      name: "kubectl_exec",
      description: "Execute a command in a container",
      inputSchema: {
      "type": "object",
      "properties": {
        "pod": { "type": "string", "description": "Pod name" },
        "command": { "type": "string", "description": "Command to execute" },
        "container": { "type": "string", "description": "Container name" },
        "namespace": { "type": "string", "description": "Namespace" }
      },
      "required": ["pod", "command"]
    }
    }
  ],
  [
    "kubectl_scale",
    {
      name: "kubectl_scale",
      description: "Scale a deployment, replicaset, or statefulset",
      inputSchema: {
      "type": "object",
      "properties": {
        "resource": { "type": "string", "description": "Resource type (deployment, replicaset, statefulset)" },
        "name": { "type": "string", "description": "Resource name" },
        "replicas": { "type": "integer", "description": "Number of replicas" },
        "namespace": { "type": "string", "description": "Namespace" }
      },
      "required": ["resource", "name", "replicas"]
    }
    }
  ],
  [
    "kubectl_rollout",
    {
      name: "kubectl_rollout",
      description: "Manage rollouts (status, history, undo, restart)",
      inputSchema: {
      "type": "object",
      "properties": {
        "action": { "type": "string", "enum": ["status", "history", "undo", "restart", "pause", "resume"], "description": "Rollout action" },
        "resource": { "type": "string", "description": "Resource type (deployment, daemonset, statefulset)" },
        "name": { "type": "string", "description": "Resource name" },
        "namespace": { "type": "string", "description": "Namespace" },
        "revision": { "type": "integer", "description": "Revision number for undo" }
      },
      "required": ["action", "resource", "name"]
    }
    }
  ],
  [
    "kubectl_port_forward",
    {
      name: "kubectl_port_forward",
      description: "Forward local port to a pod (returns connection info)",
      inputSchema: {
      "type": "object",
      "properties": {
        "resource": { "type": "string", "description": "Resource (pod/name or svc/name)" },
        "ports": { "type": "string", "description": "Port mapping (local:remote)" },
        "namespace": { "type": "string", "description": "Namespace" }
      },
      "required": ["resource", "ports"]
    }
    }
  ],
  [
    "kubectl_context",
    {
      name: "kubectl_context",
      description: "Manage kubectl contexts (list, current, use)",
      inputSchema: {
      "type": "object",
      "properties": {
        "action": { "type": "string", "enum": ["list", "current", "use"], "description": "Context action" },
        "name": { "type": "string", "description": "Context name for 'use' action" }
      },
      "required": ["action"]
    }
    }
  ],
  [
    "kubectl_top",
    {
      name: "kubectl_top",
      description: "Display resource usage (CPU/memory) for nodes or pods",
      inputSchema: {
      "type": "object",
      "properties": {
        "resource": { "type": "string", "enum": ["nodes", "pods"], "description": "Resource type" },
        "name": { "type": "string", "description": "Optional resource name" },
        "namespace": { "type": "string", "description": "Namespace for pods" },
        "containers": { "type": "boolean", "description": "Show container metrics" }
      },
      "required": ["resource"]
    }
    }
  ],
  [
    "kubectl_create",
    {
      name: "kubectl_create",
      description: "Create resources (namespace, secret, configmap, etc.)",
      inputSchema: {
      "type": "object",
      "properties": {
        "resource": { "type": "string", "description": "Resource type to create" },
        "name": { "type": "string", "description": "Resource name" },
        "namespace": { "type": "string", "description": "Namespace" },
        "fromLiteral": { "type": "object", "description": "Key-value pairs for configmap/secret" },
        "fromFile": { "type": "string", "description": "File path for configmap/secret" }
      },
      "required": ["resource", "name"]
    }
    }
  ]
]);

async function handleToolCall(name, args) {
  let argsDict = Stdlib_Option.getOr(Stdlib_JSON.Decode.object(args), {});
  let getString = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.string), "");
  let getBool = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.bool), false);
  let getInt = key => Stdlib_Option.map(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.float), v => v | 0);
  let ns = getString("namespace");
  let nsArg = ns !== "" ? [
      "-n",
      ns
    ] : [];
  switch (name) {
    case "kubectl_apply" :
      let manifest = getString("manifest");
      let filename = getString("filename");
      let dryRun = getBool("dryRun");
      let args$1 = ["apply"];
      let args$2 = args$1.concat(nsArg);
      let args$3 = dryRun ? args$2.concat(["--dry-run=client"]) : args$2;
      let args$4 = filename !== "" ? args$3.concat([
          "-f",
          filename
        ]) : args$3.concat([
          "-f",
          "-"
        ]);
      if (filename !== "") {
        return await runKubectl(args$4);
      }
      let tmpFile = "/tmp/kubectl-manifest.yaml";
      await Deno.writeTextFile(tmpFile, manifest);
      return await runKubectl(args$4.filter(a => a !== "-").concat([
        "-f",
        tmpFile
      ]));
    case "kubectl_context" :
      let action = getString("action");
      let ctxName = getString("name");
      switch (action) {
        case "current" :
          return await runKubectl([
            "config",
            "current-context"
          ]);
        case "list" :
          return await runKubectl([
            "config",
            "get-contexts"
          ]);
        case "use" :
          return await runKubectl([
            "config",
            "use-context",
            ctxName
          ]);
        default:
          return {
            TAG: "Error",
            _0: "Unknown action: " + action
          };
      }
    case "kubectl_create" :
      let resource = getString("resource");
      let resName = getString("name");
      let args$5 = [
        "create",
        resource,
        resName
      ];
      let args$6 = args$5.concat(nsArg);
      return await runKubectl(args$6);
    case "kubectl_delete" :
      let resource$1 = getString("resource");
      let resName$1 = getString("name");
      let selector = getString("selector");
      let force = getBool("force");
      let gracePeriod = getInt("gracePeriod");
      let args$7 = [
        "delete",
        resource$1
      ];
      let args$8 = resName$1 !== "" ? args$7.concat([resName$1]) : args$7;
      let args$9 = args$8.concat(nsArg);
      let args$10 = selector !== "" ? args$9.concat([
          "-l",
          selector
        ]) : args$9;
      let args$11 = force ? args$10.concat(["--force"]) : args$10;
      let args$12 = gracePeriod !== undefined ? args$11.concat([
          "--grace-period",
          gracePeriod.toString()
        ]) : args$11;
      return await runKubectl(args$12);
    case "kubectl_describe" :
      let resource$2 = getString("resource");
      let resName$2 = getString("name");
      return await runKubectl([
        "describe",
        resource$2,
        resName$2
      ].concat(nsArg));
    case "kubectl_exec" :
      let pod = getString("pod");
      let command = getString("command");
      let container = getString("container");
      let args$13 = [
        "exec",
        pod
      ];
      let args$14 = args$13.concat(nsArg);
      let args$15 = container !== "" ? args$14.concat([
          "-c",
          container
        ]) : args$14;
      let args$16 = args$15.concat([
        "--",
        "sh",
        "-c",
        command
      ]);
      return await runKubectl(args$16);
    case "kubectl_get" :
      let resource$3 = getString("resource");
      let resName$3 = getString("name");
      let selector$1 = getString("selector");
      let output = getString("output");
      let allNs = getBool("allNamespaces");
      let args$17 = [
        "get",
        resource$3
      ];
      let args$18 = resName$3 !== "" ? args$17.concat([resName$3]) : args$17;
      let args$19 = allNs ? args$18.concat(["--all-namespaces"]) : args$18.concat(nsArg);
      let args$20 = selector$1 !== "" ? args$19.concat([
          "-l",
          selector$1
        ]) : args$19;
      let args$21 = output !== "" ? args$20.concat([
          "-o",
          output
        ]) : args$20;
      return await runKubectl(args$21);
    case "kubectl_logs" :
      let pod$1 = getString("pod");
      let container$1 = getString("container");
      let since = getString("since");
      let tail = getInt("tail");
      let previous = getBool("previous");
      let args$22 = [
        "logs",
        pod$1
      ];
      let args$23 = args$22.concat(nsArg);
      let args$24 = container$1 !== "" ? args$23.concat([
          "-c",
          container$1
        ]) : args$23;
      let args$25 = since !== "" ? args$24.concat([
          "--since",
          since
        ]) : args$24;
      let args$26 = tail !== undefined ? args$25.concat([
          "--tail",
          tail.toString()
        ]) : args$25;
      let args$27 = previous ? args$26.concat(["--previous"]) : args$26;
      return await runKubectl(args$27);
    case "kubectl_port_forward" :
      let resource$4 = getString("resource");
      let ports = getString("ports");
      return {
        TAG: "Ok",
        _0: `Port forward: kubectl port-forward ` + resource$4 + ` ` + ports + ` ` + (
          ns !== "" ? "-n " + ns : ""
        ) + `\nNote: Run this command manually as it requires an interactive session.`
      };
    case "kubectl_rollout" :
      let action$1 = getString("action");
      let resource$5 = getString("resource");
      let resName$4 = getString("name");
      let revision = getInt("revision");
      let args$28 = [
        "rollout",
        action$1,
        resource$5 + `/` + resName$4
      ];
      let args$29 = args$28.concat(nsArg);
      let args$30 = revision !== undefined ? args$29.concat([`--to-revision=` + revision.toString()]) : args$29;
      return await runKubectl(args$30);
    case "kubectl_scale" :
      let resource$6 = getString("resource");
      let resName$5 = getString("name");
      let replicas = Stdlib_Option.getOr(getInt("replicas"), 1);
      return await runKubectl([
        "scale",
        resource$6 + `/` + resName$5,
        `--replicas=` + replicas.toString()
      ].concat(nsArg));
    case "kubectl_top" :
      let resource$7 = getString("resource");
      let resName$6 = getString("name");
      let containers = getBool("containers");
      let args$31 = [
        "top",
        resource$7
      ];
      let args$32 = resName$6 !== "" ? args$31.concat([resName$6]) : args$31;
      let args$33 = resource$7 === "pods" ? args$32.concat(nsArg) : args$32;
      let args$34 = containers ? args$33.concat(["--containers"]) : args$33;
      return await runKubectl(args$34);
    default:
      return {
        TAG: "Error",
        _0: "Unknown tool: " + name
      };
  }
}

export {
  namespace,
  runKubectl,
  tools,
  handleToolCall,
}
/* tools Not a pure module */
