// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

async function runKustomize(args) {
  let cmd = $$Deno.Command.$$new("kustomize", args, undefined);
  let output = await cmd.output();
  if (output.success) {
    return {
      TAG: "Ok",
      _0: $$Deno.Command.stdoutText(output)
    };
  } else {
    return {
      TAG: "Error",
      _0: $$Deno.Command.stderrText(output)
    };
  }
}

async function runKubectl(args) {
  let cmd = $$Deno.Command.$$new("kubectl", args, undefined);
  let output = await cmd.output();
  if (output.success) {
    return {
      TAG: "Ok",
      _0: $$Deno.Command.stdoutText(output)
    };
  } else {
    return {
      TAG: "Error",
      _0: $$Deno.Command.stderrText(output)
    };
  }
}

let tools = Object.fromEntries([
  [
    "kustomize_build",
    {
      name: "kustomize_build",
      description: "Build a kustomization directory into YAML manifests",
      inputSchema: {
      "type": "object",
      "properties": {
        "path": { "type": "string", "description": "Path to kustomization directory" },
        "output": { "type": "string", "description": "Output file path (optional, stdout if not set)" },
        "enableHelm": { "type": "boolean", "description": "Enable Helm chart inflation" },
        "loadRestrictor": { "type": "string", "enum": ["LoadRestrictionsNone", "LoadRestrictionsRootOnly"], "description": "Load restriction policy" }
      },
      "required": ["path"]
    }
    }
  ],
  [
    "kustomize_apply",
    {
      name: "kustomize_apply",
      description: "Build and apply kustomization to cluster (kubectl apply -k)",
      inputSchema: {
      "type": "object",
      "properties": {
        "path": { "type": "string", "description": "Path to kustomization directory" },
        "namespace": { "type": "string", "description": "Target namespace" },
        "dryRun": { "type": "boolean", "description": "Run in dry-run mode" },
        "serverSide": { "type": "boolean", "description": "Use server-side apply" },
        "prune": { "type": "boolean", "description": "Prune resources not in manifest" }
      },
      "required": ["path"]
    }
    }
  ],
  [
    "kustomize_create",
    {
      name: "kustomize_create",
      description: "Create a new kustomization.yaml file",
      inputSchema: {
      "type": "object",
      "properties": {
        "path": { "type": "string", "description": "Directory for new kustomization" },
        "resources": { "type": "array", "items": { "type": "string" }, "description": "Resource files to include" },
        "namespace": { "type": "string", "description": "Namespace to set" },
        "namePrefix": { "type": "string", "description": "Prefix for all resource names" },
        "nameSuffix": { "type": "string", "description": "Suffix for all resource names" }
      },
      "required": ["path"]
    }
    }
  ],
  [
    "kustomize_edit_add",
    {
      name: "kustomize_edit_add",
      description: "Add items to kustomization (resource, patch, configmap, secret, etc.)",
      inputSchema: {
      "type": "object",
      "properties": {
        "path": { "type": "string", "description": "Path to kustomization directory" },
        "type": { "type": "string", "enum": ["resource", "patch", "configmap", "secret", "base", "label", "annotation"], "description": "What to add" },
        "name": { "type": "string", "description": "Name (for configmap/secret)" },
        "file": { "type": "string", "description": "File path to add" },
        "literal": { "type": "string", "description": "Literal value (key=value)" }
      },
      "required": ["path", "type"]
    }
    }
  ],
  [
    "kustomize_edit_set",
    {
      name: "kustomize_edit_set",
      description: "Set values in kustomization (namespace, nameprefix, namesuffix, image)",
      inputSchema: {
      "type": "object",
      "properties": {
        "path": { "type": "string", "description": "Path to kustomization directory" },
        "type": { "type": "string", "enum": ["namespace", "nameprefix", "namesuffix", "image"], "description": "What to set" },
        "value": { "type": "string", "description": "Value to set" },
        "newName": { "type": "string", "description": "New image name (for image type)" },
        "newTag": { "type": "string", "description": "New image tag (for image type)" },
        "digest": { "type": "string", "description": "Image digest (for image type)" }
      },
      "required": ["path", "type", "value"]
    }
    }
  ],
  [
    "kustomize_edit_remove",
    {
      name: "kustomize_edit_remove",
      description: "Remove items from kustomization",
      inputSchema: {
      "type": "object",
      "properties": {
        "path": { "type": "string", "description": "Path to kustomization directory" },
        "type": { "type": "string", "enum": ["resource", "patch", "transformer", "buildmetadata"], "description": "What to remove" },
        "file": { "type": "string", "description": "File path to remove" }
      },
      "required": ["path", "type", "file"]
    }
    }
  ],
  [
    "kustomize_cfg",
    {
      name: "kustomize_cfg",
      description: "Run kustomize cfg commands (cat, count, grep, tree)",
      inputSchema: {
      "type": "object",
      "properties": {
        "command": { "type": "string", "enum": ["cat", "count", "grep", "tree"], "description": "cfg subcommand" },
        "path": { "type": "string", "description": "Path to resources" },
        "pattern": { "type": "string", "description": "Pattern for grep" }
      },
      "required": ["command", "path"]
    }
    }
  ],
  [
    "kustomize_version",
    {
      name: "kustomize_version",
      description: "Show kustomize version",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ]
]);

async function handleToolCall(name, args) {
  let argsDict = Stdlib_Option.getOr(Stdlib_JSON.Decode.object(args), {});
  let getString = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.string), "");
  let getBool = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.bool), false);
  let getArray = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.array), []);
  switch (name) {
    case "kustomize_apply" :
      let path = getString("path");
      let ns = getString("namespace");
      let dryRun = getBool("dryRun");
      let serverSide = getBool("serverSide");
      let prune = getBool("prune");
      let args$1 = [
        "apply",
        "-k",
        path
      ];
      let args$2 = ns !== "" ? args$1.concat([
          "-n",
          ns
        ]) : args$1;
      let args$3 = dryRun ? args$2.concat(["--dry-run=client"]) : args$2;
      let args$4 = serverSide ? args$3.concat(["--server-side"]) : args$3;
      let args$5 = prune ? args$4.concat(["--prune"]) : args$4;
      return await runKubectl(args$5);
    case "kustomize_build" :
      let path$1 = getString("path");
      let output = getString("output");
      let enableHelm = getBool("enableHelm");
      let loadRestrictor = getString("loadRestrictor");
      let args$6 = [
        "build",
        path$1
      ];
      let args$7 = enableHelm ? args$6.concat(["--enable-helm"]) : args$6;
      let args$8 = loadRestrictor !== "" ? args$7.concat([
          "--load-restrictor",
          loadRestrictor
        ]) : args$7;
      let args$9 = output !== "" ? args$8.concat([
          "-o",
          output
        ]) : args$8;
      return await runKustomize(args$9);
    case "kustomize_cfg" :
      let command = getString("command");
      let path$2 = getString("path");
      let pattern = getString("pattern");
      let args$10 = [
        "cfg",
        command,
        path$2
      ];
      let args$11 = pattern !== "" && command === "grep" ? args$10.concat([pattern]) : args$10;
      return await runKustomize(args$11);
    case "kustomize_create" :
      let path$3 = getString("path");
      let resources = Stdlib_Array.filterMap(getArray("resources"), Stdlib_JSON.Decode.string);
      let ns$1 = getString("namespace");
      let namePrefix = getString("namePrefix");
      let nameSuffix = getString("nameSuffix");
      let kustomization = `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
` + (
        ns$1 !== "" ? "namespace: " + ns$1 + "\n" : ""
      ) + (
        namePrefix !== "" ? "namePrefix: " + namePrefix + "\n" : ""
      ) + (
        nameSuffix !== "" ? "nameSuffix: " + nameSuffix + "\n" : ""
      ) + `resources:
` + resources.map(r => "  - " + r).join("\n") + `
`;
      let filePath = path$3 + "/kustomization.yaml";
      await Deno.writeTextFile(filePath, kustomization);
      return {
        TAG: "Ok",
        _0: "Created " + filePath
      };
    case "kustomize_edit_add" :
      let path$4 = getString("path");
      let addType = getString("type");
      let addName = getString("name");
      let file = getString("file");
      let literal = getString("literal");
      let args$12 = [
        "edit",
        "add",
        addType
      ];
      let args$13;
      let exit = 0;
      switch (addType) {
        case "annotation" :
        case "label" :
          args$13 = args$12.concat([literal]);
          break;
        case "base" :
        case "patch" :
        case "resource" :
          args$13 = args$12.concat([file]);
          break;
        case "configmap" :
        case "secret" :
          exit = 1;
          break;
        default:
          args$13 = args$12;
      }
      if (exit === 1) {
        let args$14 = args$12.concat([addName]);
        let args$15 = file !== "" ? args$14.concat(["--from-file=" + file]) : args$14;
        args$13 = literal !== "" ? args$15.concat(["--from-literal=" + literal]) : args$15;
      }
      let cmd = $$Deno.Command.$$new("kustomize", args$13, path$4);
      let output$1 = await cmd.output();
      if (output$1.success) {
        return {
          TAG: "Ok",
          _0: $$Deno.Command.stdoutText(output$1)
        };
      } else {
        return {
          TAG: "Error",
          _0: $$Deno.Command.stderrText(output$1)
        };
      }
    case "kustomize_edit_remove" :
      let path$5 = getString("path");
      let removeType = getString("type");
      let file$1 = getString("file");
      let cmd$1 = $$Deno.Command.$$new("kustomize", [
        "edit",
        "remove",
        removeType,
        file$1
      ], path$5);
      let output$2 = await cmd$1.output();
      if (output$2.success) {
        return {
          TAG: "Ok",
          _0: $$Deno.Command.stdoutText(output$2)
        };
      } else {
        return {
          TAG: "Error",
          _0: $$Deno.Command.stderrText(output$2)
        };
      }
    case "kustomize_edit_set" :
      let path$6 = getString("path");
      let setType = getString("type");
      let value = getString("value");
      let newName = getString("newName");
      let newTag = getString("newTag");
      let digest = getString("digest");
      let args$16;
      if (setType === "image") {
        let imgArg = newName !== "" && newTag !== "" ? value + `=` + newName + `:` + newTag : (
            newTag !== "" ? value + `:` + newTag : (
                digest !== "" ? value + `@` + digest : value
              )
          );
        args$16 = [
          "edit",
          "set",
          "image",
          imgArg
        ];
      } else {
        args$16 = [
          "edit",
          "set",
          setType,
          value
        ];
      }
      let cmd$2 = $$Deno.Command.$$new("kustomize", args$16, path$6);
      let output$3 = await cmd$2.output();
      if (output$3.success) {
        return {
          TAG: "Ok",
          _0: $$Deno.Command.stdoutText(output$3)
        };
      } else {
        return {
          TAG: "Error",
          _0: $$Deno.Command.stderrText(output$3)
        };
      }
    case "kustomize_version" :
      return await runKustomize(["version"]);
    default:
      return {
        TAG: "Error",
        _0: "Unknown tool: " + name
      };
  }
}

export {
  runKustomize,
  runKubectl,
  tools,
  handleToolCall,
}
/* tools Not a pure module */
