// Generated by ReScript, PLEASE EDIT WITH CARE


function getWithDefault(key, $$default) {
  let v = Deno.env.get(key);
  if (v !== undefined) {
    return v;
  } else {
    return $$default;
  }
}

let Env = {
  getWithDefault: getWithDefault
};

let decoder = new TextDecoder();

function stdoutText(output) {
  return decoder.decode(output.stdout);
}

function stderrText(output) {
  return decoder.decode(output.stderr);
}

function $$new(cmd, argsOpt, cwdOpt) {
  let args = argsOpt !== undefined ? argsOpt : [];
  let cwd = cwdOpt !== undefined ? cwdOpt : "";
  if (cwd !== "") {
    return new (Deno.Command)(cmd, {
      args: args,
      cwd: cwd,
      stdout: "piped",
      stderr: "piped"
    });
  } else {
    return new (Deno.Command)(cmd, {
      args: args,
      stdout: "piped",
      stderr: "piped"
    });
  }
}

async function run(binary, args) {
  let cmd = $$new(binary, args, undefined);
  let result = await cmd.output();
  return [
    result.code,
    decoder.decode(result.stdout),
    decoder.decode(result.stderr)
  ];
}

let Command = {
  decoder: decoder,
  stdoutText: stdoutText,
  stderrText: stderrText,
  $$new: $$new,
  run: run
};

export {
  Env,
  Command,
}
/* decoder Not a pure module */
